#!/usr/bin/env node
// Builds js/players.js and data/values.json from live sources.
//   node scripts/build-values.mjs            # live
//   GBY_FIXTURES=scripts/fixtures node scripts/build-values.mjs   # offline, from fixtures
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import config from './config.mjs';
import { aggregate } from './aggregate.mjs';
import { log } from './lib.mjs';
import * as fantasycalc from './sources/fantasycalc.mjs';
import * as espn from './sources/espn.mjs';
import * as sleeper from './sources/sleeper.mjs';
import * as fantasypros from './sources/fantasypros.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

const [fc, es, sl, fp] = await Promise.all([
  fantasycalc.load({ numTeams: config.numTeams }), espn.load(), sleeper.load(), fantasypros.load(),
]);

if (fc.players.size === 0 && es.players.size === 0 && fp.players.size === 0) {
  log('no source returned data — keeping existing js/players.js'); process.exit(1);
}

const { players, qbUplift } = aggregate({ fc, espn: es, sleeper: sl, fp });
const meta = {
  generatedAt: new Date().toISOString(),
  weights: config.weights,
  qbUplift,
  sources: [
    { id: 'fantasycalc', label: fantasycalc.label, players: fc.players.size },
    { id: 'espn', label: espn.label, players: es.players.size },
    { id: 'fantasypros', label: fantasypros.label, players: fp.players.size, skipped: !!fp.skipped },
    { id: 'sleeper', label: sleeper.label, players: sl.momentum.size },
  ],
  count: players.length,
};

const banner = `// GENERATED by scripts/build-values.mjs — do not edit by hand.\n// ${meta.generatedAt} · ${players.length} players · sources: ${meta.sources.filter(s => s.players).map(s => s.label).join(', ')}\n`;
fs.writeFileSync(path.join(root, 'js/players.js'), `${banner}const PLAYERS = ${JSON.stringify(players)};\nconst PLAYERS_META = ${JSON.stringify(meta)};\n`);
fs.mkdirSync(path.join(root, 'data'), { recursive: true });
fs.writeFileSync(path.join(root, 'data/values.json'), JSON.stringify({ meta, players }, null, 1));
log(`wrote ${players.length} players (QB superflex uplift ×${qbUplift})`);
