#!/usr/bin/env node
// Builds js/players.js and data/values.json from live sources.
//   node scripts/build-values.mjs            # live
//   GBY_FIXTURES=scripts/fixtures node scripts/build-values.mjs   # offline, from fixtures
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import config from './config.mjs';
import { aggregate } from './aggregate.mjs';
import { log } from './lib.mjs';
import { appendHistory } from './history.mjs';
import { buildScoring } from './scoring.mjs';
import * as fantasycalc from './sources/fantasycalc.mjs';
import * as espn from './sources/espn.mjs';
import * as sleeper from './sources/sleeper.mjs';
import * as fantasypros from './sources/fantasypros.mjs';
import * as pihs from './sources/pihs.mjs';
import * as nflverse from './sources/nflverse.mjs';
import * as sleeperproj from './sources/sleeperproj.mjs';
import { buildModel } from './model.mjs';
import { phaseWeights } from './aggregate.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

// Schedule first: the current week decides preseason vs. in-season weighting and which weeks to project.
const nfl = await nflverse.load();
const week = nfl.week ?? 1;
const [fc, es, sl, fp, ph, pj] = await Promise.all([
  fantasycalc.load({ numTeams: config.numTeams }), espn.load(), sleeper.load(), fantasypros.load({ week }), pihs.load(),
  sleeperproj.load({ season: nfl.season, fromWeek: week }),
]);
// bye weeks: ESPN first, schedule as a fallback
for (const t of new Set(nfl.games.flatMap(g => [g.home, g.away]))) if (!es.byes[t]) {
  for (let w = 1; w <= 18; w++) if (!nfl.games.some(g => g.week === w && (g.home === t || g.away === t))) { es.byes[t] = w; break; }
}
const model = buildModel({ nfl, proj: pj, meta: sl.meta });
log(`model: week ${model.week}, ${model.all?.length || 0} players modeled (usage ${model.usagePlayers}, projection weeks ${model.projWeeks}), phase t=${phaseWeights(week).t.toFixed(2)}`);

if (fc.players.size === 0 && es.players.size === 0 && fp.players.size === 0) {
  log('no source returned data — keeping existing js/players.js'); process.exit(1);
}

const { players, qbUplift, weights } = aggregate({ fc, espn: es, sleeper: sl, fp, pihs: ph, model });
const meta = {
  generatedAt: new Date().toISOString(),
  week, season: nfl.season,
  weights,            // effective weights this week (after the preseason → in-season hand-off)
  qbUplift,
  sources: [
    { id: 'fantasycalc', label: fantasycalc.label, players: fc.players.size },
    { id: 'model', label: 'GBY projection model', players: model.all?.length || 0, detail: `Sleeper projections (${pj.weeks.size} wks) + nflverse usage + matchups + Vegas lines` },
    { id: 'espn', label: espn.label, players: weights.espn ? es.players.size : 0, retired: !weights.espn },
    { id: 'fantasypros', label: fp.type === 'ros' ? 'FantasyPros ROS' : fantasypros.label, players: fp.players.size, skipped: !!fp.skipped },
    { id: 'pihs', label: pihs.label, players: ph.players.size, skipped: !!ph.skipped },
    { id: 'sleeper', label: sleeper.label, players: sl.momentum.size },
  ],
  count: players.length,
};

const banner = `// GENERATED by scripts/build-values.mjs — do not edit by hand.\n// ${meta.generatedAt} · ${players.length} players · sources: ${meta.sources.filter(s => s.players).map(s => s.label).join(', ')}\n`;
fs.writeFileSync(path.join(root, 'js/players.js'), `${banner}const PLAYERS = ${JSON.stringify(players)};\nconst PLAYERS_META = ${JSON.stringify(meta)};\n`);
fs.mkdirSync(path.join(root, 'data'), { recursive: true });
fs.writeFileSync(path.join(root, 'data/values.json'), JSON.stringify({ meta, players }, null, 1));
log(`wrote ${players.length} players (QB superflex uplift ×${qbUplift})`);

// ---- value history: one snapshot per day, used by the player pages' charts ----
const hist = appendHistory(path.join(root, 'data/history.json'), meta.generatedAt.slice(0, 10), players);
log(`history: ${hist.dates.length} snapshots, ${Object.keys(hist.players).length} players`);

// ---- weekly fantasy points (Sleeper stats) for player pages, rankings, rosters ----
await buildScoring(path.join(root, 'data/scoring.json'), players);
